import { defineSaasConfig } from '@mmshark/saas-config'

export default defineSaasConfig({
  product: {
    id: 'starter-saas',
    name: 'Starter SaaS',
    description: 'Nuxt and AWS Amplify SaaS starter with workspace billing.',
    urls: {
      app: 'https://app.starter.example.com',
      landing: 'https://starter.example.com',
      support: 'https://github.com/mmshark/starter-nuxt-amplify-saas/issues',
      privacy: 'https://starter.example.com/privacy',
      terms: 'https://starter.example.com/terms',
    },
  },
  brand: {
    logo: '/favicon.ico',
    favicon: '/favicon.ico',
    colors: {
      primary: 'blue',
      neutral: 'slate',
    },
  },
  localization: {
    defaultLocale: 'en',
    locales: [
      { code: 'en', name: 'English' },
      { code: 'es', name: 'Español' },
    ],
    defaultCurrency: 'USD',
  },
  billing: {
    plans: [
      {
        id: 'free',
        name: 'Free',
        description: 'Perfect for getting started with basic usage',
        currency: 'USD',
        prices: { monthly: 0, yearly: 0 },
        features: ['1 project', '1 team member', '1 GB storage', 'Community support'],
        limits: { projects: 1, 'team-members': 1, 'storage-gb': 1 },
      },
      {
        id: 'starter',
        name: 'Starter',
        description: 'Great for small teams and early projects',
        currency: 'USD',
        prices: { monthly: 5.95, yearly: 65 },
        features: ['5 projects', 'Up to 3 team members', '10 GB storage', 'Email support'],
        limits: { projects: 5, 'team-members': 3, 'storage-gb': 10 },
      },
      {
        id: 'pro',
        name: 'Pro',
        description: 'Advanced features for growing teams',
        currency: 'USD',
        prices: { monthly: 29, yearly: 310 },
        trialDays: 14,
        features: [
          'Unlimited projects',
          'Up to 10 team members',
          '100 GB storage',
          'Priority support',
          'Advanced analytics',
        ],
        limits: { projects: null, 'team-members': 10, 'storage-gb': 100 },
      },
      {
        id: 'enterprise',
        name: 'Enterprise',
        description: 'Full-scale solution for large organizations',
        currency: 'USD',
        prices: { monthly: 99, yearly: 1068 },
        features: [
          'Unlimited everything',
          'Unlimited team members',
          '1 TB storage',
          '24/7 dedicated support',
          'Advanced analytics',
          'Custom integrations',
          'SLA guarantee',
        ],
        limits: { projects: null, 'team-members': null, 'storage-gb': 1000 },
      },
    ],
  },
  entitlements: {
    features: [
      { id: 'basic-dashboard', name: 'Basic Dashboard' },
      { id: 'advanced-analytics', name: 'Advanced Analytics' },
      { id: 'audit-logs', name: 'Audit Logs' },
      { id: 'data-export', name: 'Data Export' },
      { id: 'webhooks', name: 'Webhooks' },
      { id: 'api-access', name: 'API Access' },
      { id: 'priority-support', name: 'Priority Support' },
      { id: 'custom-branding', name: 'Custom Branding' },
      { id: 'sso', name: 'Single Sign-On' },
      { id: 'custom-integrations', name: 'Custom Integrations' },
    ],
    plans: {
      free: ['basic-dashboard'],
      starter: ['basic-dashboard', 'data-export'],
      pro: ['basic-dashboard', 'advanced-analytics', 'audit-logs', 'data-export', 'webhooks'],
      enterprise: [
        'basic-dashboard',
        'advanced-analytics',
        'audit-logs',
        'data-export',
        'webhooks',
        'api-access',
        'priority-support',
        'custom-branding',
        'sso',
        'custom-integrations',
      ],
    },
  },
  auth: {
    signupFields: ['email'],
    providers: [],
    mfa: 'off',
  },
  shell: {
    multiWorkspace: true,
    workspaceSwitcher: true,
    darkMode: true,
    onboarding: false,
  },
})
