version: '3'

tasks:
  clean.nuxt:
    desc: "Clean the project from Nuxt related files"
    cmds:
      - find . -type d \( -name ".nuxt" -o -name ".playground" -o -name ".output" -o -name "dist" \) -exec rm -rf {} +
  clean.amplify:
    desc: "Clean the project from Nuxt related files"
    cmds:
      - find . -type d \( -name ".amplify" \) -exec rm -rf {} +
  clean.test:
    desc: "Clean the project from test related files"
    cmds:
      - find . -type d \( -name "test-results" \) -exec rm -rf {} +
  clean.logs:
    desc: "Clean the project from logs"
    cmds:
      - find . -type f \( -name "*.log" \) -exec rm -rf {} +
  clean.node:
    desc: "Clean the project from node_modules"
    cmds:
      - find . -type d \( -name "node_modules" \) -exec rm -rf {} +
  clean:
    desc: "Clean the project"
    deps:
      - clean.nuxt
      - clean.amplify
      - clean.test
      - clean.logs
      - clean.node

  amplify.checks:
    desc: "Check the Amplify project"
    cmds:
      - 'test -n "$AWS_PROFILE" || (echo "Error: AWS_PROFILEX is not set" && exit 1)'
      - 'test -n "$SANDBOX_STACK_NAME" || (echo "Error: SANDBOX_STACK_NAME environment variable is not set" && exit 1)'
      # - 'test -n "$STRIPE_SECRET_KEY" || (echo "Error: STRIPE_SECRET_KEY environment variable is not set" && exit 1)'

  amplify.bootstrap:
    desc: "Bootstrap the Amplify project"
    deps:
      - amplify.checks
    cmds:
      - corepack enable
      - pnpm install
      - pnpm backend:sandbox:delete
      - pnpm backend:sandbox:init
      - pnpm amplify:sandbox:generate-outputs
      - pnpm amplify:sandbox:generate-graphql-client-code

  amplify.seed:
    desc: "Seed the Amplify sandbox"
    deps:
      - amplify.checks
    cmds:
      - pnpm backend:sandbox:seed



