import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'fs';
import { defineNuxtConfig } from 'nuxt/config';
import { join } from 'path';

export default defineNuxtConfig({
  build: {
    transpile: ['trpc-nuxt']
  },

  hooks: {
    'build:before': async () => {
      const routers: Array<{
        name: string
        exportName: string
        importPath: string
        layerName: string
      }> = []

      console.log('🔍 [tRPC] Scanning layers for tRPC routers...')

      // Import nuxt dynamically to access layers
      const { useNuxt } = await import('@nuxt/kit')
      const nuxt = useNuxt()

      // Scan all layers for tRPC routers
      for (const layer of nuxt.options._layers || []) {
        const routersPath = join(layer.cwd, 'server/trpc/routers')

        if (!existsSync(routersPath)) continue

        const files = readdirSync(routersPath).filter(f =>
          f.endsWith('.ts') && !f.endsWith('.d.ts') && f !== 'index.ts'
        )

        for (const file of files) {
          const routerName = file.replace('.ts', '')
          const layerName = layer.config?.name?.replace('@starter-nuxt-amplify-saas/', '')

          if (!layerName) {
            console.warn(`[tRPC] Skipping router ${routerName}: layer has no name`)
            continue
          }

          routers.push({
            name: routerName,
            exportName: `${routerName}Router`,
            importPath: `@starter-nuxt-amplify-saas/${layerName}/server/trpc/routers/${routerName}`,
            layerName,
          })

          console.log(`   ✓ Found: ${routerName} (from ${layerName})`)
        }
      }

      // Generate TypeScript code
      const code = `// ==========================================
// Auto-generated by tRPC layer
// DO NOT EDIT - Changes will be overwritten
// Generated at: ${new Date().toISOString()}
// ==========================================

import { router } from '@starter-nuxt-amplify-saas/trpc/server/trpc/trpc'

// Layer router imports
${routers.map(r => `import { ${r.exportName} } from '${r.importPath}' // from ${r.layerName}`).join('\n')}

// Composed application router
export const appRouter = router({
${routers.map(r => `  ${r.name}: ${r.exportName},`).join('\n')}
})

// Type export for client usage
export type AppRouter = typeof appRouter
`

      // Generate in the server directory of the root app
      const serverDir = join(nuxt.options.rootDir, 'server/trpc')
      if (!existsSync(serverDir)) {
        mkdirSync(serverDir, { recursive: true })
      }

      // Write generated router
      const outputPath = join(serverDir, 'app-router.ts')
      writeFileSync(outputPath, code, 'utf-8')

      console.log(`✅ [tRPC] Generated router with ${routers.length} router(s) at: ${outputPath}`)
    }
  }
})
