// ==========================================
// Auto-generated by tRPC layer
// DO NOT EDIT - Changes will be overwritten
// Generated at: 2025-11-24T21:42:43.101Z
// ==========================================

import { router } from '@starter-nuxt-amplify-saas/trpc/server/trpc/trpc'

// Layer router imports


// Composed application router
export const appRouter = router({

})

// Type export for client usage
export type AppRouter = typeof appRouter
